### ISSUE TITLE
error while compiling the ShowObj

### ISSUE THREAD

**Issue by nobuyuki83** [goto-c/OpenGL#1]
An error appears while compiling the "ShowObj" demo:

![Screenshot 2020-06-24 18 26 54](https://user-images.githubusercontent.com/40525402/85529754-59e06480-b648-11ea-8be3-c7b3add826be.png)

in [CMakeLists](../blob/master/ShowObj/CMakeLists.txt), the following line needs to be changed. 
```
# glfw
set(GLFW_LIBRARY
  ../delfem2/3rd_party/glfw/src/libglfw3.a)
get_filename_component(GLFW_LIBRARY ${GLFW_LIBRARY} ABSOLUTE)
set(GLFW_INCLUDE_DIR
  ../delfem2/3rd_party/glfw/include)
```

**Comment by goto-c** [comment]
![error](https://user-images.githubusercontent.com/61488975/85555503-f57dcf00-b660-11ea-9a51-91b49965c414.gif)

I modified the CMakeLists.txt, and now the object is almost shown, but his face and legs are strange .., even though the main.cpp is the same as that for showing the garment. 
I will continue to try fixing this.

**Comment by nobuyuki83** [comment]
This line has a problem. Look at the code carefully and fix the mistake:

https://github.com/goto-c/OpenGL/blob/cc924860fedb38df14be1dad576d8b9d2a17f0af/03_ShowObj/main.cpp#L226

**Comment by goto-c** [comment]
I changed "aXYZ -> aTri_XYZ", then the image successfully shown . Thank you so much !
I tried some other models including the garment model, and they can be shown as well :)

**Comment by nobuyuki83** [comment]
Cool! Well done!
