### ISSUE TITLE
linking error for the demo "ShowTexture" 

### ISSUE THREAD

**Issue by nobuyuki83** [goto-c/OpenGL#2]
Linking the "ShowTexture" fails because the ```libglfw3.a``` is missing

![Screenshot 2020-06-24 18 33 53](https://user-images.githubusercontent.com/40525402/85530910-441f6f00-b649-11ea-976d-bc95413468c9.png)

The library path is not general in [CMakeList.txt](../blob/master/ShowTexture/CMakeLists.txt)

```
set(GLFW_LIBRARY    /Users/Chihiro/Desktop/OpenGL/glfw/src/libglfw3.a)
```

**Comment by goto-c** [comment]
The glfw/src directory was missing "libglfw3.a" file, so I added it.
And I changed to use a relative path.
