### ISSUE TITLE
Nothing is shown in the "02_ShowTexture" demo

### ISSUE THREAD

**Issue by nobuyuki83** [goto-c/OpenGL#3]
I managed to run the program on Mac, but nothing appears in the window. 

The error message says "Failed to get image"

![Screenshot 2020-06-25 22 27 23](https://user-images.githubusercontent.com/40525402/85729143-8329ef00-b733-11ea-82d3-5293d118551c.png)

**Comment by goto-c** [comment]
According to the error message, the image file might not  be read.
Could you look for the "scene1.jpg" in "pics" directory ?
This program works on my mac book air without problem .. :/
![スクリーンショット 2020-06-25 22 50 03](https://user-images.githubusercontent.com/61488975/85732388-490e1c80-b736-11ea-8ccf-c4af29e322ea.png)

**Comment by nobuyuki83** [comment]
Well, the relative path such as "../../pics/sceine1.jpg" doesn't work for the "out-of-place" build using cmake. 
To fix this problem, it is necessary to use the predefined macro. 

Look at the ```CMakeLists.txt``` in the ```03_ShowObj```. The path of the resource is defined as:

```
add_definitions(-DPATH_ROOT_DIR="${PROJECT_SOURCE_DIR}/..")
```

**Comment by goto-c** [comment]
OK ! I just fixed the CMakeLists.txt. 
How about this ?

**Comment by nobuyuki83** [comment]
you need to change this line:
```
    unsigned char *img = stbi_load("../../pics/scene1.jpg", &width, &height, &channels, 3);
```

as

```
    unsigned char *img = stbi_load(std::string(PATH_ROOT_DIR)+"pics/scene1.jpg", &width, &height, &channels, 3);
```

**Comment by goto-c** [comment]
Sorry, I have written as you show, but it doesn't work...
May I ask you what's the problem ?
![スクリーンショット 2020-06-26 14 43 52](https://user-images.githubusercontent.com/61488975/85824950-f4ad8000-b7bb-11ea-8785-383f371b501d.png)

**Comment by nobuyuki83** [comment]
You can find what's wrong by closely reading the function interface of the "stbi_load".

**Comment by nobuyuki83** [comment]
Look here: 

https://github.com/goto-c/OpenGL/blob/32115bd0fc4dc86ecdbb57c806ecca3573b64e7a/02_ShowTexture/stb_image.h#L1280

I think the first variable needs to be changed to const char*. If you are not familiar with C++'s std::string, look at this article: 
https://stackoverflow.com/questions/7352099/stdstring-to-char

**Comment by goto-c** [comment]
Thanks, I managed to fix the error, and now the white window is shown with the error message "Failed to get image". I will continue to fix this.

**Comment by nobuyuki83** [comment]
look at the file path

```cpp
std::cout << std::string(PATH_ROOT_DIR)+"pics/scene1.jpg" << std::endl;
```

**Comment by goto-c** [comment]
I could finally show the texture ! Thank you so much for helping me.
Could you please check it out ?

**Comment by nobuyuki83** [comment]
Nice! the demo ran successfully on my side.

![Screenshot 2020-06-27 07 27 57](https://user-images.githubusercontent.com/40525402/85905926-cd03f980-b847-11ea-8f3d-ae6bf569839d.png)
