### ISSUE TITLE
Normal and Texture

### ISSUE THREAD

**Issue by goto-c** [goto-c/OpenGL#4]
![スクリーンショット 2020-06-30 14 22 03](https://user-images.githubusercontent.com/61488975/86086638-29cc1200-badd-11ea-9794-fcf14a261a5c.png)

**Comment by nobuyuki83** [comment]
Is it possible to show just the direction of normal as a normal_map instead of showing texture? The fragment shader is very simple and it looks something like this:

```glsl
in vec3 normal;
void main {
  gl_FragColor = vec4(0.5*normal + 0.5)
}
```

The ```normal``` in this code is the 3D normal vector where the z-direction is the screen normal.
You will see the blue-ish shading on the object.

https://github.com/goto-c/OpenGL/blob/49768568777295dff9c67f8e0a411da0c3f1ea6d/04_ShowObjWithShader/main.cpp#L472
Please mind that the shader programming does not require VAO. The VAO makes the program look a bit complicated. 
I think you can still draw objects using "glBegin() glVertex glEnd()" commands.

**Comment by goto-c** [comment]
Thank you for a comment !
> I think you can still draw objects using "glBegin() glVertex glEnd()" commands.  

Do these commands also require shader object in that case ?

**Comment by nobuyuki83** [comment]
In legacy OpenGL, the code looks like this:

1. compile vertex shader and fragment shader to get ```shader program id```
2. before draw something, call ```glUseProgram(id_shader_program)```
3. draw a shape with glBegin, glVeretx, glEnd

> > I think you can still draw objects using "glBegin() glVertex glEnd()" commands.

> Do these commands also require shader object in that case ?

The shader is tot always required in legacy OpenGL (new OpenGL always requires shader). If the shader object is unset or glUseProgram(0)  is called, legacy OpenGL uses the "default shader".

You can take a look at my demo program. 
https://github.com/nobuyuki83/delfem2/tree/master/examples_glfwold/131_Shader

**Comment by goto-c** [comment]
OK, thanks, I will continue to check !

**Comment by nobuyuki83** [comment]
Good luck! if you get stuck in something, let me know.

**Comment by goto-c** [comment]
Excuse me, I'm sorry to bother you.
I tried various measures consulting a lot of web sites, but the normal shader just shows this grey one or nothing. 
I suppose that there is something wrong about buffer object and around it, but lots of information on the internet are conflicting with each other, so I couldn't possibly write a functional code...
Could you tell me some helpful web page or something to study with ?
![normal](https://user-images.githubusercontent.com/61488975/86355615-ecff4700-bca5-11ea-9e6e-ffd09c93aecf.png)

**Comment by nobuyuki83** [comment]
This is the desired result:

![Screenshot 2020-07-03 09 10 53](https://user-images.githubusercontent.com/40525402/86419084-320a9400-bd0d-11ea-969d-0d80118294db.png)

**Comment by nobuyuki83** [comment]
I made the pull request #5
Look carefully at my edit history and merge my edits.

**Comment by goto-c** [comment]
Thank you so much again ! I will closely review the code and learn how to make it by myself.

**Comment by nobuyuki83** [comment]
> I will closely review the code and learn how to make it by myself.

Yes, please.

You can look at the edit history by clicking the "File Changed" tab of the pull request. 
https://github.com/goto-c/OpenGL/pull/5/files
