### ISSUE TITLE
folder structure change

### ISSUE THREAD

**Issue by nobuyuki83** [goto-c/OpenGL#6]
- [x] create CMakeLists.txt below the OpenGL. Add all the demo in the subdirectory
- [x] put all the external dependencies into one folder '3rd_party'
- [x] put all the data for demo into one folder 'test_data'
- [x] put all obj parse functions into one source code 'objloader.cpp/.h'

**Comment by goto-c** [comment]
Excuse me, I wrote CMakeLists.txt like this, and put it in "OpenGL" directory.
But it didn't work and produces some errors. .
What can I do to fix ?
```
cmake_minimum_required(VERSION 2.8)
option(USE_HEADERONLY "USE_DFM2_HEADERONLY" ON)
project(OpenGL_Examples)

add_subdirectory(00_HelloWorld)
add_subdirectory(01_openwin)
add_subdirectory(02_ShowTexture)
add_subdirectory(03_ShowObj)
add_subdirectory(04_ShowObjWithShader)
```
![スクリーンショット 2020-07-06 12 35 08](https://user-images.githubusercontent.com/61488975/86553703-6d63c780-bf86-11ea-9735-97e22d8681b4.png)

**Comment by nobuyuki83** [comment]
The error message says the target name, "a.out" is used multiple times. Use a different target name for each different example.

**Comment by goto-c** [comment]
Thanks, I think it went well ! 
![スクリーンショット 2020-07-06 13 53 06](https://user-images.githubusercontent.com/61488975/86557567-832aba00-bf91-11ea-9990-8f790618f2f1.png)
And many files related to cmake was generated in "OpenGL" and each project directory.

Is this the same operation as doing ```cmake .``` in each project directory ?
If possible, I would rather make build directory as usual like
```
mkdir build
cd build
make -G Xcode ..
```
is there any way to do this ?

**Comment by nobuyuki83** [comment]
you can do out-off-source build as:

```bash
cd OpenGL
mkdir build
cd build
cmake -G Xcode ..
```

make sure that the secondary files generated from cmake will not be in this repository.

**Comment by goto-c** [comment]
![スクリーンショット 2020-07-06 15 26 39](https://user-images.githubusercontent.com/61488975/86563284-10c0d680-bf9f-11ea-82d0-46d882749a53.png)
Thanks, I succeeded in collecting all projects in a single Xcode project !
It seems so convenient :)

I marked all of the check box, so could you check them out please ?

**Comment by nobuyuki83** [comment]
I found a problem. I couldn't do the "git submodule" to download the dependency. 

```
Nobuyukis-MacBook-Pro-2:OpenGL nobuyuki$ git submodule update --init --recursive
fatal: No url found for submodule path '3rd_party/glfw' in .gitmodules
```

look at this website to fix this problem. 
https://qiita.com/u1aryz/items/8d1923da79158439eeaa

**Comment by goto-c** [comment]
I fixed the problem. Could you check it again, please ?

**Comment by nobuyuki83** [comment]
It works here. 

```objloader.cpp``` and  ```objloader.h``` is not a third party code. Move it to the other directory such as ```Opengl/src```

**Comment by goto-c** [comment]
I moved the two files to ```OpenGL/Opengl/src```.

I'd like to ask one question.
In the glfw repository (https://github.com/glfw/glfw/tree/2539d037478549a0b76bf7572dab05e1fa1a4c96/src), there isn't ```libglfw3.a```.
So when I demonstrated 03_ShowObj after these commands
```git clone https://github.com/goto-c/OpenGL.git```
```git submodule apdate --init --recursive```,
an error occurred that ```libglfw3.a```can't be found. 
Is there any measure to solve this problem somehow ?

**Comment by nobuyuki83** [comment]
> I'd like to ask one question.
> In the glfw repository (https://github.com/glfw/glfw/tree/2539d037478549a0b76bf7572dab05e1fa1a4c96/src), there isn't libglfw3.a.

you need to compile glfw to make ```libglfw3.a``` So the installation commands look like

``` bash
git clone https://github.com/goto-c/OpenGL.git
git submodule update --init --recursive,
cd 3rd_party/glfw
cmake .
make
cd ../../
mkdir build
cd build
cmake -G Xcode ..
```

**Comment by goto-c** [comment]
I could do it , thank you !

**Comment by nobuyuki83** [comment]
BTW, it's common to use folder structure ```OpenGL/src``` instead of ```OpenGL/Opengl/src```. These layout is totally up to you, but it's better not to make folder structure deep.

**Comment by goto-c** [comment]
I changed the structure.

**Comment by nobuyuki83** [comment]
add ```05_ScreenShot``` and ```openwinNewGlad``` to the project

**Comment by goto-c** [comment]
I added it, and modified readme (added demo picture, changed the usage).

**Comment by nobuyuki83** [comment]
Looks good. I think you can close this issue.

**Comment by goto-c** [comment]
OK, thank you !
