### ISSUE TITLE
Take screen shot 

### ISSUE THREAD

**Issue by nobuyuki83** [goto-c/OpenGL#7]
Make a new demo that takes screenshot images using the OpenGL function "glReadPixels". Save the screenshot image using the stb_image library.

**Comment by goto-c** [comment]
![スクリーンショット 2020-07-07 12 10 33](https://user-images.githubusercontent.com/61488975/86699299-052ae980-c04b-11ea-9d69-83883641d8f1.png)
I wrote ```glReadPixels``` like this.
I think I have to add a function from stb_image.h before ```free(pixel_data);``` to make screen shot file, but I can't figure out how to use stb_image.h as bmp encoder.. 
Could you instruct me the usage of it, please ?

**Comment by nobuyuki83** [comment]
> I think I have to add a function from stb_image.h before free(pixel_data); to make screen shot file, but I can't figure out how to use stb_image.h as bmp encoder..
> Could you instruct me the usage of it, please ?

There are instructions in the source code of stb_image

https://github.com/nothings/stb/blob/f54acd4e13430c5122cab4ca657705c84aa61b08/stb_image_write.h#L45

**Comment by goto-c** [comment]
Thanks, I didn't notice stb_image_write.h, now I checked the instruction
but I still don't understand where the output picture was saved. 
The object was shown, but an output image can't be found..

![スクリーンショット 2020-07-07 15 18 51](https://user-images.githubusercontent.com/61488975/86726441-87280c00-c065-11ea-9711-81f9442fcfee.png )

**Comment by nobuyuki83** [comment]
> The object was shown, but an output image can't be found..

whenever you specify some paths in of-the-source build, use the macro definition. I think you have already defined a maco PATH_ROOT_DIR in CMakeLists.txt.

**Comment by goto-c** [comment]
![Screen_0](https://user-images.githubusercontent.com/61488975/86735772-fe619e00-c06d-11ea-95c3-d231ee1bdb0a.png)
I made it ! 
But unfortunately, the picture is upside-down.

**Comment by nobuyuki83** [comment]
> But unfortunately, the picture is upside-down.

look here: https://github.com/nothings/stb/blob/f54acd4e13430c5122cab4ca657705c84aa61b08/stb_image_write.h#L53

**Comment by goto-c** [comment]
Thanks, I fixed it .
I have pushed all changes in my repository, so could you check it please ?

**Comment by nobuyuki83** [comment]
Checked. Looks good.
